### ISSUE TITLE
[bug/visual] Appbar background blur not working on firefox / safari / mobile (works on desktop chrome)

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/grida.co#17]
https://bridged.xyz - the app bar's bg blur won't work on non desktop chrome platforms.

*firefox*
![image](https://user-images.githubusercontent.com/16307013/98071376-b3825680-1ea6-11eb-9c4d-18bdd84b2b76.png)

*chrome*
![image](https://user-images.githubusercontent.com/16307013/98071394-c3019f80-1ea6-11eb-8f51-75e900b41dfd.png)

**Comment by You-J** [comment]
firefox doesn't support that css. I'll update it later! Thks!

**Comment by softmarshmallow** [comment]
LGTM, Thanks.
