### ISSUE TITLE
[marketing/seo] add sitemap xml

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/grida.co#32]
Adding sitemap xml will help search engines to crawl our web better.

these are options for making sitemap we have.
- https://github.com/IlusionDev/nextjs-sitemap-generator
- manual xml creation

![sitemap xml currently not available on bridged.xyz](https://user-images.githubusercontent.com/16307013/104549249-d040c480-5675-11eb-9648-9a1ff2d4a4e2.png)

**Comment by GwonHeeJun** [comment]
Closed!

Plz Check #42 PR
