### ISSUE TITLE
SignUp button position on the main page look weird.

### ISSUE THREAD

**Issue by AsheKR** [gridaco/grida.co#43]
**Describe the bug**
The buttons on the main page look weird.

**To Reproduce**
https://bridged.xyz/

**Expected behavior**
Style Issue?

**Screenshots**
![image](https://user-images.githubusercontent.com/42999044/107897732-3ecab800-6f7d-11eb-84a3-95bdc77045be.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Chrome
 - Version: 88.0.4324.150

**Comment by softmarshmallow** [comment]
Thanks for your report.
Though, The new version of website being developed under branch [`renewal`](https://github.com/bridgedxyz/bridged.xyz/tree/renewal)
![image](https://user-images.githubusercontent.com/16307013/110067522-4381cf80-7db7-11eb-940d-3a5d6093d1f1.png)

Closing.
